echo [build] > netlify.toml
echo publish = "." >> netlify.toml
echo [[redirects]] >> netlify.toml
echo from = "/*" >> netlify.toml
echo to = "/index.html" >> netlify.toml
echo status = 200 >> netlify.toml